### PR TITLE
I have changed the input statement

### PR DESCRIPTION
**Pull request by satya1657**
I think this message should look like this

### CODE REVIEW

**Comment by Satyaprkash-Sigmoid** [comment]
okay you have done a good job but could you please make it recursive

**Comment by satya1657** [comment]
okay I am doing that but this could take a little more time

**Comment by Satyaprkash-Sigmoid** [comment]
okay do that there is problem of the time

**Comment by satya1657** [comment]
okay sir!

**Comment by Satyaprkash-Sigmoid** [comment]
okay bro

**Pull request merged**
